<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Xsearch
 */
?>
<?php
/**
 * @var \Amasty\Xsearch\Block\Search\Product $block
 * @var array $products
 * phpcs:ignoreFile
 */
$products = $block->getProducts();
?>

<?php if (count($products)): ?>
    <div class="amsearch-products" data-amsearch-js="products">
       
        <div class="amsearch-wrapper-content">
            <?php foreach ($products as $id => $product): ?>
                <div class="amsearch-item product-item" data-amsearch-js="product-item"
                     data-click-url="<?= $block->escapeUrl($block->getFullLink($product['url'])) ?>">
                    <div class="amsearch-autocomplete-information">
                        <div class="information-container">
                            <div class="product details product-item-details">
                                <a class="product-item-link"
                                   href="<?= $block->escapeUrl($block->getFullLink($product['url'])) ?>"
                                   title="<?= $block->escapeHtml($block->stripTags($product['name'])); ?>">
                                    <?= /* @noEscape */ $product['name'] ?>
                                </a>
                                <?php if ($block->isShowDescription($product)):?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */ $product['description'] ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($block->getReviews()): ?>
                                    <?= /* @noEscape */ $product['reviews'] ?>
                                <?php endif; ?>
                               
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php if ($block->getNumResults() > $block->getLimit()): ?>
            <div class="amsearch-more-results">
                <a href="<?= $block->escapeUrl($block->getResultUrl()) ?>"
                   title="<?= $block->escapeHtml(__('View All'))?>"
                    class="amsearch-link">
                    <?= $block->escapeHtml(__('View All')) ?>
                    <span> (<?= $block->escapeHtml($block->getNumResults()) ?>)</span>
                </a>
            </div>
        <?php endif; ?>
    </div>

    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            $('.amasty-xsearch-form').catalogAddToCart({});
        });
    </script>
<?php endif; ?>
