<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_LayerNavigation
 * @author    Extension Team
 * @copyright Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
 // @codingStandardsIgnoreFile
?>

<?php
/**
 * Dropdown Block
 *
 * @var $block \Bss\LayerNavigation\Block\Type\Dropdown
 */
?>

<div class="items">
    <select name="layer_<?php echo $block->escapeHtml($block->getAttributeCode()) ?>" class="layer_filter_select" <?php echo $block->isMultipleMode() ? 'multiple' : '' ?> url="<?php echo $block->escapeUrl($block->getBlankUrl()) ?>" search="<?php echo $block->isSearchEnable() ? 'true' : 'false' ?>">
    <?php foreach ($block->getOptions() as $key => $option): ?>
        <option value="<?php echo $block->escapeUrl($option['value']) ?>" <?php echo $option['selected'] ? 'selected' : '' ?> <?php echo $option['disabled'] ? 'disabled' : '' ?>><?php echo $block->escapeHtml($option['label']) ?></option>
    <?php endforeach; ?>
    </select>
</div>