<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
 $meigee_helper = $this->helper('\Meigee\Universal\Helper\UniversalGeneral');
 $open_default = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'layer_accordion');
 ?>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter <?= ($open_default == 1 ? 'default-open' : '') ?>" id="layered-filter-block">
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */ $filtered ?>">
            <strong data-role="title"><?= /* @escapeNotVerified */ __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content clearfix">
            <?= $block->getChildHtml('state') ?>

            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= /* @escapeNotVerified */ __('Shopping Options') ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content" >
                    <?php  $wrapOptions = true; endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><strong><?= /* @escapeNotVerified */ __($filter->getName()) ?></strong></div>
                        <div data-role="content" class="filter-options-content"><?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= /* @escapeNotVerified */ $block->getClearUrl() ?>" class="action clear filter-clear"><i class="fa fa-times"></i><span><?= /* @escapeNotVerified */ __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
