<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_StoreCredit
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php /** @var  $block \Bss\StoreCredit\Block\Adminhtml\Order\Create\Credit */?>

<?php if ($block->getStoreCreditTotal()) : ?>
    <div class="admin__field field-apply-store-credit" data-mage-init='{
                    "Bss_StoreCredit/js/order_create": {}
                }'>
        <label class="admin__field-label"><span><?php /* @noEscape */ echo __('Store Credit') ?></span></label>
        <div>
            <?php /* @noEscape */ echo __('Customer Credit Balance:') ?>
            <span><?php /* @noEscape */ echo $block->getStoreCreditTotal(); ?></span>
        </div>
        <div class="admin__field-control">
            <input type="text" class="admin__control-text"
                id="store_credit_amount"
                value=""
                name="store_credit_amount" />
            <?php echo $block->getButtonHtml(__('Apply'), 'order.applyStoreCredit($F(\'store_credit_amount\'))') ?>
            <?php if ($block->getStoreCreditUsed()) : ?>
                <p class="added-store-credit">
                    <span><?php /* @noEscape */ echo $block->getStoreCreditUsed() ?></span>
                    <a href="#"
                        id="store_credit_remove"
                        onclick="order.applyStoreCredit(0); return false;"
                        title="<?php /* @noEscape */ echo __('Remove Store Credit') ?>"
                        class="action-remove">
                        <span><?php /* @noEscape */ echo __('Remove') ?></span>
                    </a>
                </p>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
