<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ProductAttachment
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Block
 *
 * @var $block \Bss\ProductAttachment\Block\Product\View 
 */

$helper = $block->getAttachmentHelper();

$product = $block->getProduct();
$productId = $product->getId();

$customerGroupId = $helper->getCustomerGroupId();
$storeId = $block->getStoreId();
$postUrl = $block->getBaseUrl().'productattachment/render/attachmentlist';
?>

<?php if ($helper->getShowInBlockFlag() && $helper->hasAttachment($productId)): ?>
    <div class="bss productattachment">
        <input type="hidden" id="attachment_block_productId" value="<?php echo $productId ?>">
        <input type="hidden" id="attachment_block_customerId" value="<?php echo $customerGroupId ?>">
        <input type="hidden" id="attachment_block_storeId" value="<?php echo $storeId ?>">
        <div class="productattachment_listattachment_block" style="margin-bottom:20px;">
            <?php if (!empty($product->getData('bss_productattachment'))): ?>
			<h3 style="color:#333;margin:0 0 6px 0;"><i style="font-size:18px;margin-right:6px;color:#004361;"class='fad fa-download'></i><?php echo $helper->getBlockAttachmentTitle(); ?></h3>
            <?php endif ?>
        </div>
    </div>
    <script type="text/x-magento-init">
    {
    "*": 
        {
            "Bss_ProductAttachment/js/renderblock": {
                "postUrl": "<?php echo $postUrl ?>"
            }
        }
    }
    </script>
<?php endif ?>