<?php
  $sticky_logo = $this->getChildHtml("sticky.logo");
  $sticky_logo_status = $this->getConfig('universal_general/universal_header/sticky_header_logo');
  $sticky_nav = $this->getChildHtml("sticky.catalog.topnav");
  $sticky_nav_status = $this->getConfig('universal_general/universal_header/sticky_header_nav');
  $sticky_search = $this->getChildHtml("stickySearch");
  $sticky_search_status = $this->getConfig('universal_general/universal_header/sticky_header_search');
?>

<div id="sticky-header" class="header">
  <div class="container">
    <?php if ($sticky_logo_status) : ?>
      <div class="left-wrapper">
        <?php echo ($sticky_logo_status ? $sticky_logo : ''); ?> 
      </div>
    <?php endif; ?>
    <div class="right-wrapper clearfix<?php if ($sticky_search_status) : echo ' with-search'; endif; ?>">
      <?php echo ($sticky_nav_status ? $sticky_nav : ''); ?> 
      <?php echo ($sticky_search_status ? $sticky_search : ''); ?> 
    </div>
  </div>
</div>