<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<nav class="navbar navbar-default navigation">
	<span data-action="toggle-nav" class="action nav-toggle"><i class="fa fa-bars"></i><span><?= /* @escapeNotVerified */ __('Menu') ?></span></span>
	<div class="collapse topmenu navbar-collapse">
		<ul class="nav topmenu navbar-nav" id="nav" data-mage-init='{"menu":{"responsive":true, "expanded":true, "delay": 0, "position":{"my":"left top","at":"left bottom"}}}'>
			<?= /* @escapeNotVerified */ $_menu ?>
			<?= /* @escapeNotVerified */ $block->getChildHtml() ?>
		</ul>
	</div>
</nav>