<?php 
$fbStatus = $this->helper('\Meigee\Universal\Helper\UniversalGeneral')->getCustomThemeOptionCnf('universal_facebook_block', 'status');
if($fbStatus){
$fb_url = $this->helper('\Meigee\Universal\Helper\UniversalGeneral')->getCustomThemeOptionCnf('universal_facebook_block', 'url');
 ?>
<div class="block block-fblikebox">
	<div class="block-title">
		 <strong><span><?php echo __('Facebook Like Box') ?></span></strong>
	</div>
	<div class="block-content">
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_EN/sdk.js#xfbml=1&version=v2.3";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
		<div class="fb-page" <?php echo $this->helper('\Meigee\Universal\Helper\FrontHelper')->getFbSidebar(); ?>><div class="fb-xfbml-parse-ignore"><blockquote cite="<?php echo $fb_url; ?>"><a href="<?php echo $fb_url; ?>">&nbsp;</a></blockquote></div></div>
	</div>
</div>
<?php } ?>