<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_product)->toHtml(); ?>
<div class="box-tocart">
    <div class="fieldset clearfix">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control clearfix">
				<div class="quantity-decrease" onclick="qtyDown()"><i class="fa fa-minus"></i></div>
                <input type="text"
                       name="qty"
                       id="qty"
                       min="0"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
				<div class="quantity-increase" onclick="qtyUp()"><i class="fa fa-plus"></i></div>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action btn btn-primary btn-cart tocart"
                    id="product-addtocart-button" disabled>
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
	<?php if ($block->shouldRenderQuantity()): ?>
		<script type="text/javascript">
			var qty_el = document.getElementById('qty'); 
			var qty = qty_el.value; 
			// if(qty < 2){
				// jQuery('.quantity_box_button_down').css({
				// 'visibility' : 'hidden'
				// });
			// }
			function qtyDown(){
				var qty_el = document.getElementById('qty'); 
				var qty = qty_el.value; 
				// if( qty == 2) {
				// jQuery('.quantity_box_button_down').css({
					// 'visibility' : 'hidden'
				// });
				// }
				if( !isNaN( qty ) && qty > 0 ){
				qty_el.value--;
				}         
				return false;
			}
			
			function qtyUp(){
				var qty_el = document.getElementById('qty'); 
				var qty = qty_el.value; 
				if( !isNaN( qty )) {
				qty_el.value++;
				}
				// jQuery('.quantity_box_button_down').css({
				// 'visibility' : 'visible'
				// });
				return false;
			}
		</script>
	<?php endif; ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>