<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_LayerNavigation
 * @author    Extension Team
 * @copyright Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php
 // @codingStandardsIgnoreFile
?>

<?php
/**
 * Validate Item In Admin
 *
 * @var $block \Bss\LayerNavigation\Block\Adminhtml\Template\Validate
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_LayerNavigation/js/validate_attribute": <?php echo json_encode($block->getModuleHelper()->getLayerAttrParams()); ?>
        }
    }
</script>