<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
$meigee_helper = $this->helper('\Meigee\Universal\Helper\UniversalGeneral');
$icon_status = $meigee_helper->getCustomThemeOptionCnf('universal_topcart', 'icon');
$text_status = $meigee_helper->getCustomThemeOptionCnf('universal_topcart', 'text');
$counter_status = $meigee_helper->getCustomThemeOptionCnf('universal_topcart', 'counter');
$price_status = $meigee_helper->getCustomThemeOptionCnf('universal_topcart', 'price');
?>
<?php if($icon_status || $text_status || $counter_status) { ?>
<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart title-cart clearfix" href="<?= /* @escapeNotVerified */ $block->getShoppingCartUrl() ?>"
       data-bind="scope: 'minicart_content'">
		<?php if($icon_status) { ?>
			<span class="icon"><i class="fa fa-shopping-cart"></i></span>
		<?php } ?>
		<?php if($text_status || $counter_status) { ?>
			<?php if($text_status) { ?>
			<span class="text"><?= /* @escapeNotVerified */ __('My Cart') ?></span>
			<?php } ?>
			<?php if($counter_status) { ?>
			<span class="cart-divider"></span>
			<span class="counter qty empty"
				  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
				<span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
				<span class="counter-label">
				<!-- ko if: getCartParam('summary_count') -->
					<!-- ko text: getCartParam('summary_count') --><!-- /ko -->
					<!-- ko i18n: 'items' --><!-- /ko -->
				<!-- /ko -->
				</span>
			</span>
			<?php } ?>
            <?php if($price_status) { ?>
               <!-- ko if: getCartParam('possible_onepage_checkout') -->
               <!-- ko foreach: getRegion('subtotalContainer') -->
               <!-- ko template: getTemplate() --><!-- /ko -->
               <!-- /ko -->
               <!-- /ko -->
            <?php } ?>
		<?php } ?>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": true,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
			<?= $block->getChildHtml('minicart.addons') ?>
        </div>
     <?php else: ?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
        }
    }
    </script>
</div>
<?php } ?>