<?php 
	$welcomeMessage = $block->getWelcome();
	// echo $welcomeMessage;
?>
<?php // switch ($block->getShowPart()):
   //  case 'welcome': ?>
        <p class="welcome" data-bind="scope: 'customer'">
            
			<!-- ko if: customer().fullname  -->
            <span class="logged-in" data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1! ', '%1'));?>').replace('%1', customer().firstname)">
            </span>
			<span class="tagline">The Glazing Supply Company</span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span class="not-logged-in" data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"></span>
            <!-- /ko -->
        </p>

        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php // break; ?>
<?php // endswitch; ?>