<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_CustomSearchPage
 * @author    Extension Team
 * @copyright Copyright (c) 2020-2021 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct*/
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    $meigee_helper = $this->helper('\Meigee\Universal\Helper\UniversalGeneral');
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        // $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $grid_columns = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'grid_columns');
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $grid_columns = '';
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $lightbox_status = $meigee_helper->getCustomThemeOptionCnf('universal_lightbox', 'lightbox_status');
    $lightbox_listing_status = $meigee_helper->getCustomThemeOptionCnf('universal_lightbox', 'lightbox_listing');
    $quickview_status = $this->helper('WeltPixel\Quickview\Helper\Data')->getConfig('weltpixel_quickview/general/enable_product_listing');
    $quickview_btn = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'quickview_btn');
    $product_name = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'product_name');
    $product_price = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'product_price');
    $cart_btn = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'cart_btn');
    $compare_btn = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'compare_btn');
    $wishlist_btn = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'wishlist_btn');
    $mailtofriend_btn = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'mailtofriend_btn');
    $name_align = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'product_name_aligment');
    $image_hover_status = $meigee_helper->getCustomThemeOptionCnf('universal_image_hover', 'image_hover_status');
    $front_helper = $this->helper('\Meigee\Universal\Helper\FrontHelper');
    $labels_type = $meigee_helper->getCustomThemeOptionCnf('universal_labels', 'label_type');
    $label_new = $meigee_helper->getCustomThemeOptionCnf('universal_labels', 'label_new');
    $label_sale = $meigee_helper->getCustomThemeOptionCnf('universal_labels', 'label_sale');
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode .' '. $grid_columns  ?>">
        <ol class="products clearfix list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info clearfix" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                        <div class="image-wrapper">
                            <?php
                            $hoverImage = $image_hover_status ? $_product->getHoverImage() : false;
                            if ($hoverImage) {
                                $hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                    ->init($_product, 'hover_image')
                                    ->setImageFile($hoverImage)
                                    ->getUrl();
                                $productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>$hoverImageUrl));
                            }
                            else
                            {
                                $productImage = $block->getImage($_product, $imageDisplayArea);
                            }

                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            if($front_helper->isProductNew($_product) || $front_helper->isProductSale($_product) || $front_helper->isProductOnlyLeft($_product)){
                                echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_product) && $front_helper->isProductSale($_product)) || ($front_helper->isProductNew($_product) && $front_helper->isProductOnlyLeft($_product)) ? ' two-items' : '').'">';
                                if($front_helper->isProductNew($_product) && $label_new) {
                                    echo '<span class="label-new">'.__('new').'</span>';
                                }
                                if($front_helper->isProductOnlyLeft($_product) && $label_sale) {
                                    echo $front_helper->isProductOnlyLeft($_product);
                                } elseif($front_helper->isProductSale($_product) && $label_sale) {
                                    echo '<span class="label-sale">'.__('sale').'</span>';
                                }
                                echo '</div>';
                            }
                            if($quickview_btn && $quickview_status) { ?>
                                <div class="quickview-wrapper">
                                    <a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_product->getEntityId()); ?>" class="weltpixel-quickview"><i class="fa fa-eye"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
                                </div>
                            <?php }
                            if($lightbox_status && $lightbox_listing_status){
                                ?>
                                <a href="<?php echo $productImage->getImageUrl();  ?>" data-toggle="lightbox" class="lightbox-button" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
                                    <i class="fa fa-search"></i>
                                </a>
                                <?php
                            }
                            // Product Image ?>

                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                        </div>
                        <div class="product details product-item-details">
							<span class="item-number-cat">
						<?php /* @escapeNotVerified */ echo 'Item No. ' ?> <!--adds item no to catalog/search pages -->
							<span style="font-weight: bold; text-transform: uppercase;">
								<?php /* @escapeNotVerified */echo $_product->getSku() ?> <!--adds item no to catalog/search pages -->
							</span>
						</span>
							
							
                            <?php if($product_name){
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <strong class="product name product-item-name <?php echo $name_align; ?>">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>

                                </strong>

                                <a class="more_details" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    View Details
                                </a>




                            <?php }
                            if($viewMode != 'list'){ ?>
                                <?= $block->getProductDetailsHtml($_product);
                            } else { ?>
                                <?=  $block->getProductDetailsHtml($_product);
                            } ?>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?php
                            if($viewMode != 'list'){
                                if($product_price){ ?>
                                    <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                <?php }
                            } else { ?>
                                <div class="price-availability-block clearfix">
                                    <?php if($product_price){
                                        /* @escapeNotVerified */ echo $block->getProductPrice($_product);
                                        echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_product)->toHtml();
                                    }
                                    if ($_product->getIsSalable()): ?>
                                        <?php if($block->getBackOrderStatus($_product) == 0): ?>
                                            <div class="stock available"><?= /* @escapeNotVerified */ __('Availability') ?><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <?php if ($_product->isInStock() && $block->getProductQty($_product) > 0 && $block->getSalableQty($_product) > 0): ?>
                                                <div class="stock available"><?= /* @escapeNotVerified */ __('Availability') ?><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <div class="stock unavailable"><?= /* @escapeNotVerified */ __('Availability') ?><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                </div>
                            <?php } ?>
                            <div class="product-item-inner">
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                           class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                                <?php if($viewMode != 'list'){ ?>
                                    <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_product)->toHtml(); ?>
                                <?php } ?>
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <?php if($cart_btn){ ?>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <a class="more_details" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                                View Details
                                            </a>
                                        </div>
                                    <?php } ?>
                                    <?php if($compare_btn || $wishlist_btn || $mailtofriend_btn){ ?>
                                        <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                            <?php if ($mailtofriend_btn){ ?>
                                                <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>" class="action mailto friend" title="<?php /* @escapeNotVerified */ echo __('Email') ?>"><i class="fa fa-envelope-o"></i></a>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                                <div class="price-availability-block clearfix">
                                    <?php if ($_product->getIsSalable()): ?>
                                        <?php if($block->getBackOrderStatus($_product) == 0): ?>
                                            <div class="stock available"><?= /* @escapeNotVerified */ __('') ?><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <?php if ($_product->isInStock() && $block->getProductQty($_product) > 0 && $block->getSalableQty($_product) > 0): ?>
                                                <div class="stock available"><?= /* @escapeNotVerified */ __('') ?><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <div class="stock unavailable"><?= /* @escapeNotVerified */ __('') ?><span><?= /* @escapeNotVerified */ __('') ?></span></div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
        <?= $block->getToolbarHtml() ?>
    </div>
    <!--
    < ?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
        echo $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
    ? >
    -->
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
					"product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
				}
            }
        }
        </script>
    <?php endif; ?>
    <script type="text/javascript">
        require(["jquery"], function(jQuery)
        {
            function listingBanner() {
                if(jQuery('.category-description .listing-banner').length){
                    var mode = jQuery('.listing-banner').data('mode');
                    var position = jQuery('.listing-banner').data('position');
                    banner1 = jQuery('.listing-banner');
                    if(jQuery('.listing-banner-wrapper').length == 0) {
                        banner = banner1.clone();
                        banner = banner.wrap("<li class='item listing-banner-wrapper'></li>");
                        banner.parent().hide();
                        if(!jQuery('.category-description').find('.listing-banner-wrapper').length) {
                            banner.parent().appendTo(jQuery('.category-description'));
                        }
                    }
                    switch (mode){
                        case 'grid':
                            if(jQuery('.catalog-category-view .products-grid').length){
                                banner.parent().show();
                                jQuery('.products-grid').parents('.col-main').find('.category-description li.item').css('display', 'block');
                                // jQuery('.products-grid li.listing-banner-wrapper').remove();
                                if(jQuery('.products-grid li.listing-banner-wrapper').length == 0) {
                                    if (position <= jQuery('.products-grid li.item').length + 1) {
                                        jQuery('.products-grid li.item:nth-of-type(' + (position-1) + ')').after(jQuery('.category-description .listing-banner-wrapper'));
                                    } else {
                                        jQuery('.products-grid').parents('.main-container').find('.category-description li.item').css('display', 'none');
                                    }
                                }
                            }
                            break;
                        case 'list':
                            if(jQuery('.catalog-category-view .products-list').length){
                                if(jQuery('.products-list li.listing-banner-wrapper').length == 0) {
                                    banner.parent().show();
                                    jQuery('.products-list').parents('.col-main').find('.category-description li.item').css('display', 'block');
                                    jQuery('.products-list li.item:nth-of-type(' + (position-1) + ')').after(jQuery('.listing-banner-wrapper'));
                                }
                            }
                            break;
                    }
                }
            }

            jQuery(document).ready(function(){
                listingBanner();
            });
        });
    </script>
<?php endif; ?>
