<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_LayerNavigation
 * @author    Extension Team
 * @copyright Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php
 // @codingStandardsIgnoreFile
?>

<?php
/**
 * Category View Template
 *
 * @var $block \Bss\LayerNavigation\Block\Navigation\Category
 */
?>

<?php if ($block->canShowBlock()): ?>
    <?php
        $filters = $block->getFilters();
        $layerConfig = $block->getLayerConfiguration($filters);
        $buttonSubmit = $block->getModuleHelper()->isButtonSubmit();
        $filtered = count($block->getLayer()->getState()->getFilters());

    ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
    <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
        <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
    </div>
    <div class="block-content filter-content" data-mage-init='{"Bss_LayerNavigation/js/ajax_layered": <?php echo $layerConfig ?>}' >

        
        <?php echo $block->getChildHtml('state') ?>

        <?php if ($block->getLayer()->getState()->getFilters()): ?>
            <div class="block-actions filter-actions">
                <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
            </div>
        <?php endif; ?>

        <?php $wrapOptions = false; ?>
        <?php foreach ($filters as $key => $filter): ?>
            <?php if ($filter->getItemsCount()): ?>
                <?php if (!$wrapOptions): ?>
                    <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php echo __('Shopping Options') ?></strong>
                    <div class="filter-options" id="narrow-by-list" data-role="content">
                <?php  $wrapOptions = true; endif; ?>
                <div data-role="bss_collapsible" class="filter-options-item" attribute="<?php echo $block->escapeHtml($filter->getRequestVar()) ?>">
                    <div data-role="bss_title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                    <div data-role="bss_content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->setFilter($filter)->render($filter); ?>

                    </div>

                </div>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if ($buttonSubmit): ?>
            <button id="bss_button_submit" type="button" name="apply_filter" ><?php echo __('Apply Filter')?></button>
        <?php endif; ?>

        <?php if ($wrapOptions): ?>
            </div>
        <?php endif; ?>

        <?php echo $block->getChildHtml('layer_additional_info'); ?>
    </div>
</div>
<?php endif; ?>
<?php echo $block->getChildHtml('compatible_with_infinite_scroll_bss'); ?>