<?php
/**
  * @author     DCKAP <extensions@dckap.com>
  * @package    DCKAP_Ordersearch
  * @copyright  Copyright (c) 2016 DCKAP Inc (http://www.dckap.com)
  * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */

// @codingStandardsIgnoreFile
$productCollection = $block->getProducts();?>
<div class="products_list">
<?php if(count($productCollection)):?>
	<?php foreach($productCollection as $product):?>
		<div class="products_content" data-name="<?php echo $product->getName();?>">			
			<div class="product_details">
				<?php echo $product->getName();?>								
			</div>			
		</div>
	<?php endforeach;?>
<?php else:?>
	<div class="products_content">
	<?php echo __("Your search returned no results");?>
	</div>
<?php endif;?>
</div>	
	