<?php $registry = $this->_helperFactory->get('Magento\Framework\Registry'); ?>
        <?php $_productId = $registry->registry('product')->getId() ?>
        <?php $helper = $this->helper('[Vendor]\[Namespace]\Helper\Data'); ?>
        <?php $childProducts = $helper->getChildProducts($_productId);
        if ( !empty($childProducts) ):?>
        <div class="out-of-stock-child-products">
            <div class="col-sm-12">
                <div class="col-sm-12">
                    <label class="label" for="product_id" style="font-weight: bold"><span><?php echo __('Please select a product') ?></span></label>
                    <div class="control">
                        <select name="product_id" id="product_id" title="<?php echo __('Please select a product') ?>"
                                class="input-text">
                            <option value=""><?php echo __('Please select a product.') ?></option>
                            <?php foreach ($childProducts as $key => $value): ?>
                                <option value="<?php echo $key ?>"><?php echo $value ?></option>
                            <?php endforeach; ?>
                        </select>
                        <div class="product-error"
                             style="color: red; display: none"><?php echo __('Please select a product.') ?></div>
                    </div>
                </div>
            </div>
        </div>