<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_B2bRegistration
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * New Customer block template
 *
 * @var \Bss\B2bRegistration\Block\Form\Login\Info $block
 */
?>
<?php 
    $enable = $block->isEnable();
    $enableShortCut = $block->isEnableShortcutLink();
    $shortCutLinkText = $block->getShortcutLinkText();
    $b2bCreateUrl = $block->getUrlB2bAccountCreate();
?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php echo $block->escapeHtml(__('New Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
		<p><?= $block->escapeHtml(__('Request an account to gain access to purchase FHC products, software and services online. You will also have access to our latest offers and stay up to date with the latest FHC news and information. Requests are reviewed within 24 hours, and you may call (888) 295-4531 to expedite account creation.')) ?></p>
		<p><?= $block->escapeHtml(__('Registered customers have access to these great benefits:')) ?></p>
		<ul class="new_cust"><li><?= $block->escapeHtml(__('See Your Company Pricing')) ?></li>
		<li><?= $block->escapeHtml(__('Buy Online 24/7 and Save on Shipping Costs')) ?></li>
		<li><?= $block->escapeHtml(__('Access Your Order History')) ?></li>
		<li><?= $block->escapeHtml(__('Manage your FHC Consumables, Tools, and Hardware Purchases')) ?></li></ul>  
        <div class="actions-toolbar">
            <?php if ($enable): ?>
                <div class="primary b2b-create">
                    <a href="<?php echo $block->escapeUrl($b2bCreateUrl) ?>" class="action create primary"><span><?php echo $block->escapeHtml(__($shortCutLinkText)) ?></span></a>
                </div>
            <?php endif ?>
			
			<!-- Hidden until issue with displaying the wrong template is fixed
			< ?php if (($enable && $block->getRegistration()->isAllowed()) || !$enable): ?>
                <div class="second-primary">
                    <a href="< ?php echo $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span>< ?php echo $block->escapeHtml(__('Architectural Account')) ?></span></a>
					<span class="arch-info">Architects, Engineers, Specifiers, and Design professionals can register for an FHC Architectural Account. Architectural Accounts provide a number of benefits, services, and technical sales support.</span>
                </div>
            < ?php endif; ?>
            -->
        </div>
    </div>
</div>
