<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_LayerNavigation
 * @author    Extension Team
 * @copyright Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
 // @codingStandardsIgnoreFile
?>

<?php
/**
 * Add Loading Product
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div id="layered-filter-block-container" class="layered-filter-block-container">
    <?php echo $block->getChildHtml() ?>
</div>
<div id="bss_overlay" class="bss_overlay">
    <div class="bss_loadding">
        <img src="<?php echo $block->getViewFileUrl('Bss_LayerNavigation::img/loading.gif'); ?>" alt="Loading...">
    </div>
</div>
