<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CheckoutSuccessPage
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block Magento\Framework\View\Element\Template */ ?>

<?php $post = $block->getPostData();?>

<form id="print-order-guest" name="guest_post" method="post" action="<?= $block->getUrl('sales/guest/view')?>">
    <input type="hidden" name="oar_order_id" value ="<?= $post['oar_order_id'] ?>">
    <input type="hidden" name="oar_billing_lastname" value ="<?= $post['oar_billing_lastname'] ?>">
    <input type="hidden" name="oar_type" value ="email">
    <input type="hidden" name="oar_email" value ="<?= $post['oar_email'] ?>">
    <input type="hidden" name="oar_zip" value ="">
    <button type="submit" class="action primary continue color-changing prt"><span class="button-label"><?php echo __('Print Order') ?></span></button>
</form>

<script type="text/x-magento-init">
    {
        "#print-order-guest": {
            "Bss_CheckoutSuccessPage/js/print-trigger": {}
        }
    }
</script>