<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CheckoutSuccessPage
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block Bss\CheckoutSuccessPage\Block\Main */ ?>
<?php foreach ($block->getTotals() as $code => $total): ?>
    <?php if ($total->getBlockName()): ?>
        <?php echo $block->getChildHtml($total->getBlockName(), false); ?>
    <?php else:?>
    <tr class="<?php /* @escapeNotVerified */ echo $code?>">
        <th colspan="5" <?php /* @escapeNotVerified */ echo $block->getLabelProperties()?> scope="row">
            <?php if ($total->getStrong()):?>
            <strong><?php echo $block->escapeHtml($total->getLabel());?></strong>
            <?php else:?>
            <?php echo $block->escapeHtml($total->getLabel());?>
            <?php endif?>
        </th>
        <td <?php /* @escapeNotVerified */ echo $block->getValueProperties()?> data-th="<?php echo $block->escapeHtml($total->getLabel());?>">
            <?php if ($total->getStrong()):?>
            <strong><?php /* @escapeNotVerified */ echo $block->formatValue($total) ?></strong>
            <?php else:?>
            <?php /* @escapeNotVerified */ echo $block->formatValue($total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach?>