<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SimpleProductStock
 * @author     Extension Team
 * @copyright  Copyright (c) 2019-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

use Magento\Catalog\Model\Product;

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Bss\SimpleProductStock\Block\Product\View\Type\Simple */?>

<?php $_product = $block->getProduct() ?>
<?php /* @var $_product Product */ ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span>
                <?= /* @escapeNotVerified */ __('In stock -') . $block->getProductStock() . __(' Remaining') ?>
            </span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span>
                <?= /* @escapeNotVerified */ __('Out of stock') ?>
            </span>
        </div>
    <?php endif; ?>
<?php endif; ?>
