<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';
    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
	
	$widget_type = $this->getData('widget_type');
	if($widget_type == 'bestsellers') {
		$items = $block->getBestSellersCollection()->getItems();
	} elseif($widget_type == 'newproducts') {
		$items = $block->getNewProductsCollection()->getItems();
	} elseif($widget_type == 'featuredcategory') {
		$items = $block->getFeaturedCategoryProductsCollection()->getItems();
	} elseif($widget_type == 'saleproducts') {
		$items = $block->getSaleProductsCollection()->getItems();
	} else {
		$items = $block->getProductCollection()->getItems();
	}

    $showWishlist = true;
    $showCompare = true;
	$mailtofriend_btn = false;
    $showCart = true;
    // $templateType =  \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    // $templateType = false;
    $description = false;
	
	$meigee_helper = $this->helper('\Meigee\Universal\Helper\UniversalGeneral');
	$lightbox_status = $meigee_helper->getCustomThemeOptionCnf('universal_lightbox', 'lightbox_status');
	$lightbox_widget_status = $meigee_helper->getCustomThemeOptionCnf('universal_lightbox', 'lightbox_home');

	$quickview_status = $this->helper('WeltPixel\Quickview\Helper\Data')->getConfig('weltpixel_quickview/general/enable_product_listing');
	$quickview_btn = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'quickview_btn');
	
	$name_align = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'product_name_aligment');
	$stock_status = $meigee_helper->getCustomThemeOptionCnf('universal_product_listing', 'stock_status');
	$widget_id = $block->getData('widget_id');
	
	// $visibleProducts       = $block->getVisibleProducts();
    // $visibleProductsTablet = $block->getVisibleProductsTablet();
    // $visibleProductsMobile = $block->getVisibleProductsMobile();
    // $pagination            = $block->getPagination();
	$visibleProducts       = $block->getData('visible_products');
    $visibleProductsTablet = $block->getData('visible_products_tablet');
    $visibleProductsMobile = $block->getData('visible_products_mobile');
    
    $pagination            = $block->getData('pagination');
	
	$type_price = 'widget-product-grid-'.$widget_id;
	
	$labels_type = $meigee_helper->getCustomThemeOptionCnf('universal_labels', 'label_type');
	$label_new = $meigee_helper->getCustomThemeOptionCnf('universal_labels', 'label_new');
	$label_sale = $meigee_helper->getCustomThemeOptionCnf('universal_labels', 'label_sale');

	$front_helper = $this->helper('\Meigee\Universal\Helper\FrontHelper');
	$image_hover_status = $meigee_helper->getCustomThemeOptionCnf('universal_image_hover', 'image_hover_status');
?>
    <div class="block widget block-products-list widget-slider <?php /* @escapeNotVerified */ echo $mode; ?>" id="widget-products-<?php echo $widget_id; ?>">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class=" products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode .' '. $type; ?>">
                <div class="product-items owl-carousel owl-theme">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item'. (count($items) <= 4 ? ' col-sm-3' : '') .'">' : '</div><div class="item'. (count($items) <= 4 ? ' col-sm-3' : '') .'">' ?>
                        <div class="product-item-info clearfix">
                            <div class="image-wrapper">
								<?php 
									$hoverImage = $image_hover_status ? $_item->getHoverImage() : false;
									if ($hoverImage) {
										$hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
														  ->init($_item, 'hover_image')
														  ->setImageFile($hoverImage)
														  ->getUrl();
										$productImage = $block->getImage($_item, $image, array('data-hover-image'=>$hoverImageUrl));
									}
									else
									{
										$productImage = $block->getImage($_item, $image);
									}
									
									if($front_helper->isProductNew($_item) || $front_helper->isProductSale($_item) || $front_helper->isProductOnlyLeft($_item)){
										echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_item) && $front_helper->isProductSale($_item)) || ($front_helper->isProductNew($_item) && $front_helper->isProductOnlyLeft($_item)) ? ' two-items' : '').'">';
											if($front_helper->isProductNew($_item) && $label_new) {
												echo '<span class="label-new">'.__('new').'</span>';
											}
											if($front_helper->isProductOnlyLeft($_item) && $label_sale) {
												echo $front_helper->isProductOnlyLeft($_item);
											} elseif($front_helper->isProductSale($_item) && $label_sale) {
												echo '<span class="label-sale">'.__('sale').'</span>';
											}
										echo '</div>';
									}
								?>
								<?php if($quickview_btn && $quickview_status) { ?>
									<div class="quickview-wrapper">
		                                <a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_item->getEntityId()); ?>" class="weltpixel-quickview"><i class="fa fa-eye"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
		                            </div>
	                            <?php } ?>
                                <?php if($lightbox_status && $lightbox_widget_status){ ?>
                                    <a href="<?php echo $block->getImage($_item, $image)->getImageUrl();  ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $block->escapeHtml($_item->getName()); ?>" title="<?php echo __('Lightbox'); ?>">
                                        <i class="fa fa-search"></i>
                                    </a>
                                <?php } ?>
                                <button class="btn btn-primary btn-details">
									<span>
										<i class="fa fa-eye"></i>
									</span>
								</button>
								<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo" tabindex="-1">
									<?php echo $block->getImage($_item, $image)->toHtml(); ?>
								</a>
                            </div>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name <?php echo $name_align; ?>">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                <?php endif; ?>

                                <?php echo $block->getProductPriceHtml($_item, $type_price); ?>
                                <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_item)->toHtml(); ?>
								<?php if($stock_status != 4 && $stock_status != 2) {
                                    if ($_item->getIsSalable()): ?>
                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif;
                                } ?>
								<div class="product-item-inner">
									<?php if($block->getProductPriceHtml($_item, $type_price) || $showCart || $showWishlist || $showCompare){ ?>
										<div class="product actions product-item-actions">
											<?php if ($showCart){ ?>
												<div class="actions-primary">
													<?php if ($_item->isSaleable()){ ?>
														<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
															<button data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
																type="button"
																	title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																	class="action tocart btn btn-default btn-cart">
																<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
															</button>
														<?php else: ?>
															<?php
																$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
															?>
															<button data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																type="button"
																	title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																	class="action tocart btn btn-default btn-cart">
																<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
															</button>
														<?php endif; ?>
													<?php }else{ ?>
														<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><span><?php echo __('Read more') ?></span></a>
													<?php } ?>
												</div>
											<?php } ?>
											<?php if($showWishlist || $showCompare || $mailtofriend_btn){ ?>
												<div data-role="add-to-links" class="actions-secondary">
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
														<a href="#"
														   class="action towishlist"
														   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
														   data-action="add-to-wishlist"
														   role="button">
															<i class="fa fa-heart"></i>
														</a>
													<?php endif; ?>
													<?php if($showCompare){
														$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
														<a href="#"
														   class="action tocompare"
														   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
														   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
														   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
														   role="button">
															<i class="fa fa-exchange"></i>
														</a>
													<?php } ?>
													<?php if ($mailtofriend_btn){ ?>
														<a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_item) ?>" class="action mailto friend" title="<?php /* @escapeNotVerified */ echo __('Email') ?>"><i class="fa fa-envelope-o"></i></a>
													<?php } ?>
												</div>
											<?php } ?>
										</div>
									<?php } ?>
								</div>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</div>' : '' ?>
                    <?php endforeach ?>
                </div>
            </div>
			<div class="owl-buttons"></div>
			<?php 
			if(count($items) > 4){ ?>
				<script type="text/javascript">
                    require(["jquery"], function(jQuery)
                    {
                        require(["MeigeeCarousel"], function(owlCarousel)
                        {
                            homeSlider<?php echo $widget_id; ?> = jQuery('#widget-products-<?php echo $widget_id; ?> .product-items');
                            homeSlider<?php echo $widget_id; ?>.owlCarousel({
                                margin: 0,
                                responsive:{
                                    0:{
                                        items:<?php echo $visibleProductsMobile; ?>
                                    },
                                    767:{
                                        items:<?php echo $visibleProductsTablet; ?>
                                    },
                                    1007:{
                                        items:<?php echo $visibleProducts; ?>
                                    },
                                    1331:{
                                        items:<?php echo $visibleProducts; ?>
                                    }
                                },
                                smartSpeed: 500,
                                dots: <?php echo $pagination; ?>,
                                loop: true,
                                nav: true,
								navContainer: '#widget-products-<?php echo $widget_id; ?> .owl-buttons',
                                navText: ['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>']
                            }); 
							jQuery(document).ready(function(){
                                // homeSlider<?php // echo $widget_id; ?> = jQuery('#widget-products-<?php // echo $widget_id; ?> .product-items');
                                // if(!jQuery('#widget-products-<?php // echo $widget_id; ?>').prev('.widget-title').find('.owl-nav-wrapper').length) {
                                //     navContainer = jQuery('<div class="owl-nav-wrapper clearfix" />');
                                //     navButtons = jQuery('#widget-products-<?php // echo $widget_id; ?>').find('.owl-nav');
                                //     navContainer.appendTo(jQuery('#widget-products-<?php // echo $widget_id; ?>').prev('.widget-title'));
                                //     navButtons.appendTo(jQuery('#widget-products-<?php // echo $widget_id; ?>').prev('.widget-title').find('.owl-nav-wrapper'));
                                // }

                              /*  jQuery('#widget-products-<?php // echo $widget_id; ?>').prev('.widget-title').find('.owl-nav .owl-next').click(function(){
                                 homeSlider<?php // echo $widget_id; ?>.trigger('owl.next');
                               });
                               jQuery('#widget-products-<?php // echo $widget_id; ?>').prev('.widget-title').find('.owl-nav .owl-prev').click(function(){
                                 homeSlider<?php // echo $widget_id; ?>.trigger('owl.prev');
                               }); */
                            });
                      });
                  }); 
                </script>
			<?php } else {
				  echo $block->getPagerHtml();
				}
			?>
        </div>
    </div>
<?php endif;?>
