<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * @category   BSS
 * @package    Bss_AvaTaxCustom
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
	$isBackorderProduct = $block->isBackorderProduct();
	if ($isBackorderProduct) :
?>
<style type="text/css">
	.product-info-main .product-info-price .product-info-price-inner .stock {
		display: none;
	}
</style>
<?php
	endif;
?>
<?php
	if ($block->isBackorderGlobal()) :
?>
<script type="text/javascript">
	window.isBackorderGlobal = true;
</script>
<?php endif; ?>