<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currency = $currencysymbol->getStore()->getCurrentCurrencyCode();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$meigee_helper = $this->helper('\Meigee\Universal\Helper\UniversalGeneral');
$layout = $meigee_helper->getCustomThemeOptionCnf('universal_layout', 'site_layout');
?>
<?php 
/* Header1 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_default')){ ?>
  <div class="header-wrapper">
    <header class="page-header">
      <div class="container">
        <div class="panel header">
          <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
          <div class="header content">
            <?php echo $this->getChildHtml("logo"); ?> 
            <?php echo $this->getChildHtml("under.logo"); ?> 
          </div>
        </div>
        <?php echo $this->getChildHtml("header.welcome"); ?> 
        <div class="right-block clearfix">
            <div class="language-currency-wrapper">
              <div class="language-currency-block">
                <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                <span class="currency"><?php echo $currency; ?></span>
                <i class="fa fa-caret-down"></i>
              </div>
              <div class="language-currency-dropdown">
                <?php echo $this->getChildHtml("store_language"); ?> 
                <?php echo $this->getChildHtml("currency"); ?>
              </div>
            </div>
            <?php echo $this->getChildHtml("topSearch"); ?> 
            <?php echo $this->getChildHtml("minicart"); ?>
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <div class="menu-inner clearfix">
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
          </div>
        </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>

<?php 
/* Header2 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_wine_2')){ ?>
  <div class="header-wrapper vertical-header">  
    <header class="page-header header-15">
      <div class="container">
        <div class="quick-access clearfix">
          <div class="language-currency-wrapper">
            <div class="language-currency-block">
              <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
              <span class="currency"><?php echo $currency; ?></span>
              <i class="fa fa-caret-down"></i>
            </div>
            <div class="language-currency-dropdown">
              <?php echo $this->getChildHtml("store_language"); ?> 
              <?php echo $this->getChildHtml("currency"); ?>
            </div>
          </div>
          <?php echo $this->getChildHtml("header.links"); ?>  
        </div> 
        <div class="panel header">
          <div class="header content">
            <?php echo $this->getChildHtml("header2.logo"); ?> 
            <?php echo $this->getChildHtml("under.logo"); ?> 
          </div>
        </div>
        <?php echo $this->getChildHtml("header.welcome"); ?> 
        <?php echo $this->getChildHtml("topSearch"); ?> 
      </div>
      <div class="bottom-block">        
          <div class="menu-wrapper">
            <div class="container">
            <?php echo $this->getChildHtml("minicart"); ?>
            <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>          
              <div class="menu-inner clearfix">
                <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
              </div>
            </div>
          </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("universal.vertical.header.block"); ?> 
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>
<?php 
/* Header3 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_electronics')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-16">
      <div class="top-block">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <?php echo $this->getChildHtml("header.welcome"); ?>
              <div class="pull-left currency-wrapper">
                <?php echo $this->getChildHtml("currency"); ?>
              </div>
              <div class="pull-left language-wrapper">
                <?php echo $this->getChildHtml("store_language"); ?> 
              </div>
              <?php echo $this->getChildHtml("header.links"); ?> 
            </div>
          </div>
        </div>
      </div>
      <div class="middle-block">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="panel header">
                <div class="header content">
                  <?php echo $this->getChildHtml("header16.logo"); ?> 
                  <?php echo $this->getChildHtml("under.logo"); ?> 
                </div>
              </div>
              <div class="quick-access clearfix">
                <?php echo $this->getChildHtml("topSearch"); ?>
                <?php echo $this->getChildHtml("universal.header.text.banners"); ?> 
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <div class="menu-inner clearfix">
            <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?></div>
            <?php echo $this->getChildHtml("minicart"); ?>            
          </div>
        </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>
<?php
/* Header4 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_food_2')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-7">
      <?php if($layout == "boxed-layout") { ?>
        <div class="container">
      <?php } ?>
        <div class="panel header">
          <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
          <div class="header content">
            <?php echo $this->getChildHtml("header7.logo"); ?> 
            <?php echo $this->getChildHtml("under.logo"); ?> 
          </div>
        </div>
        <?php echo $this->getChildHtml("header.welcome"); ?> 
        <div class="menu-block pull-left">
          <div class="wrapper-menu clearfix">
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
          </div>
        </div>
        <div class="right-block clearfix">
            <div class="language-currency-wrapper">
              <div class="language-currency-block">
                <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                <span class="currency"><?php echo $currency; ?></span>
                <i class="fa fa-caret-down"></i>
              </div>
              <div class="language-currency-dropdown">
                <?php echo $this->getChildHtml("store_language"); ?> 
                <?php echo $this->getChildHtml("currency"); ?>
              </div>
            </div>
            <?php echo $this->getChildHtml("topSearch"); ?> 
            <?php echo $this->getChildHtml("minicart"); ?>
            <?php echo $this->getChildHtml("header.links"); ?> 
        </div>
        <?php if($layout == "boxed-layout") { ?>
          </div>
        <?php } ?>
        <div class="menu-wrapper">
          <div class="container">
          </div>
        </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>
<?php
/* Header5 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_design')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-2">
      <?php if($layout == "boxed-layout") { ?>
        <div class="container">
      <?php } ?>
        <div class="panel header">
          <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
          <div class="header content">
            <?php echo $this->getChildHtml("header.design.logo"); ?> 
            <?php echo $this->getChildHtml("under.logo"); ?> 
          </div>
        </div>
        <?php echo $this->getChildHtml("header.welcome"); ?> 
        <div class="menu-block pull-left">
          <div class="wrapper-menu clearfix">
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
          </div>
        </div>
        <div class="right-block clearfix">
            <div class="language-currency-wrapper">
              <div class="language-currency-block">
                <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                <span class="currency"><?php echo $currency; ?></span>
                <i class="fa fa-caret-down"></i>
              </div>
              <div class="language-currency-dropdown">
                <?php echo $this->getChildHtml("store_language"); ?> 
                <?php echo $this->getChildHtml("currency"); ?>
              </div>
            </div>
            <?php echo $this->getChildHtml("topSearch"); ?> 
            <?php echo $this->getChildHtml("minicart"); ?>
            <?php echo $this->getChildHtml("header.links"); ?> 
        </div>
        <?php if($layout == "boxed-layout") { ?>
          </div>
        <?php } ?>
        <div class="menu-wrapper">
          <div class="container">
          </div>
        </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>
<?php
/* Header6 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_grocery')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-23">
        <div class="top-block-2">
          <div class="container">
            <div class="row">
              <div class="col-md-6 col-sm-12 col-xs-12 header-links">
                <?php echo $this->getChildHtml("universal.grocery.header.custom.links"); ?>
              </div>
              <div class="col-md-3 hidden-sm hidden-xs"><?php echo $this->getChildHtml("header.welcome"); ?></div>
              <div class="col-md-3 col-sm-2 col-xs-4">
                <div class="language-currency-wrapper">
                  <div class="language-currency-block">
                    <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                    <span class="currency"><?php echo $currency; ?></span>
                    <i class="fa fa-caret-down"></i>
                  </div>
                  <div class="language-currency-dropdown">
                    <?php echo $this->getChildHtml("store_language"); ?> 
                    <?php echo $this->getChildHtml("currency"); ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="top-block">
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div class="panel header">
                  <div class="header content">
                    <?php echo $this->getChildHtml("header23.logo"); ?> 
                    <?php echo $this->getChildHtml("under.logo"); ?> 
                  </div>
                </div>
                <div class="pull-left">
                  <?php echo $this->getChildHtml("universal.grocery.header.text.banners"); ?>
                </div>
                <div class="quick-access clearfix">
                  <?php echo $this->getChildHtml("topSearch"); ?> 
                  <?php echo $this->getChildHtml("minicart"); ?>
                  <?php echo $this->getChildHtml("header.links"); ?>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="menu-wrapper">
          <div class="container">
            <div class="menu-inner clearfix">
              <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
              <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?></div>
            </div>
          </div>
        </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>
<?php
/* Header7 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_food')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-17">
        <div class="top-block">
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div class="panel header">
                  <div class="header content">
                    <?php echo $this->getChildHtml("header17.logo"); ?> 
                    <?php echo $this->getChildHtml("under.logo"); ?> 
                  </div>
                </div>
                <div class="pull-left">
                  <?php echo $this->getChildHtml("header.welcome"); ?>
                </div>
                <div class="quick-access clearfix">
                  <div class="language-currency-wrapper">
                    <div class="language-currency-block">
                      <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                      <span class="currency"><?php echo $currency; ?></span>
                      <i class="fa fa-caret-down"></i>
                    </div>
                    <div class="language-currency-dropdown">
                      <?php echo $this->getChildHtml("store_language"); ?> 
                      <?php echo $this->getChildHtml("currency"); ?>
                    </div>
                  </div>
                  <?php echo $this->getChildHtml("minicart"); ?>
                  <?php echo $this->getChildHtml("header.links"); ?>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="menu-wrapper">
          <div class="container">
            <div class="col-md-9 menu-inner clearfix">
              <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
              <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?></div>
            </div>
            <div class="col-md-3 pull-right">
              <?php echo $this->getChildHtml("topSearch"); ?> 
            </div>
          </div>
        </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>

<?php 
/* Header8 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_cars')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-31">
      <div class="top-block">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="pull-left">
                <?php echo $this->getChildHtml("header.welcome"); ?>
              </div>
              <div class="language-currency-block clearfix">
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("currency"); ?>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="middle-block">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="header content">
                <?php echo $this->getChildHtml("header31.logo"); ?> 
                <?php echo $this->getChildHtml("under.logo"); ?> 
              </div>
              <?php echo $this->getChildHtml("universal.cars.header.block"); ?>
              <div class="right-block">
                <?php echo $this->getChildHtml("header.links"); ?> 
                <?php echo $this->getChildHtml("minicart"); ?>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <div class="row">
            <div class="wrapper-menu clearfix">
              <div class="col-md-3 search-block">
                <?php echo $this->getChildHtml("topSearch"); ?> 
              </div>
              <div class="col-md-9 menu-inner">
                <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
                <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>
<?php 
/* Header9 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_hardware')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-16">
      <div class="top-block">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <?php echo $this->getChildHtml("header.welcome"); ?>
              <div class="pull-left currency-wrapper">
                <?php echo $this->getChildHtml("currency"); ?>
              </div>
              <div class="pull-left language-wrapper">
                <?php echo $this->getChildHtml("store_language"); ?> 
              </div>
              <?php echo $this->getChildHtml("header.links"); ?> 
            </div>
          </div>
        </div>
      </div>
      <div class="middle-block">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="panel header">
                <div class="header content">
                  <?php echo $this->getChildHtml("header16_2.logo"); ?> 
                  <?php echo $this->getChildHtml("under.logo"); ?> 
                </div>
              </div>
              <div class="quick-access clearfix">
                <?php echo $this->getChildHtml("topSearch"); ?>
                <?php echo $this->getChildHtml("universal.header.hardware.text.banners"); ?> 
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <div class="menu-inner clearfix">
            <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?></div>
            <?php echo $this->getChildHtml("minicart"); ?>            
          </div>
        </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>

<?php 
/* Header10 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_lingerie')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-32">
      <div class="top-block">
        <div class="container">
          <div class="row">
            <div class="col-md-4 col-sm-4 left-block">
                <?php echo $this->getChildHtml("topSearch"); ?>
            </div>
            <div class="col-md-4 col-sm-4 a-center">
              <div class="panel header">
                <div class="header content">
                  <?php echo $this->getChildHtml("header32.logo"); ?> 
                  <?php echo $this->getChildHtml("under.logo"); ?> 
                </div>
              </div>
            </div>
            <div class="col-md-4 col-sm-4 quick-access-wrapper pull-right">
              <div class="quick-access">
                <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
                <div class="language-currency-wrapper">
                  <div class="language-currency-block">
                    <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                    <span class="currency"><?php echo $currency; ?></span>
                    <i class="fa fa-caret-down"></i>
                  </div>
                  <div class="language-currency-dropdown">
                    <?php echo $this->getChildHtml("store_language"); ?> 
                    <?php echo $this->getChildHtml("currency"); ?>
                  </div>
                </div>
                <?php echo $this->getChildHtml("minicart"); ?>
                <?php echo $this->getChildHtml("header.links"); ?> 
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <div class="menu-inner clearfix">
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
          </div>
        </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>

<?php 
/* Header11 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_sport')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-27">
      <div class="top-block">
        <div class="container">
          <div class="panel header">
            <div class="header content">
              <?php echo $this->getChildHtml("header2.7.logo"); ?> 
              <?php echo $this->getChildHtml("under.logo"); ?> 
            </div>
          </div>
          <?php echo $this->getChildHtml("header.welcome"); ?>
          <div class="menu-block pull-left clearfix">
            <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
          </div>
          <div class="right-wrapper">
              <div class="language-currency-wrapper">
                <div class="language-currency-block">
                  <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                  <span class="currency"><?php echo $currency; ?></span>
                  <i class="fa fa-caret-down"></i>
                </div>
                <div class="language-currency-dropdown">
                  <?php echo $this->getChildHtml("store_language"); ?> 
                  <?php echo $this->getChildHtml("currency"); ?>
                </div>
              </div>
              <?php echo $this->getChildHtml("topSearch"); ?>
              <?php echo $this->getChildHtml("minicart"); ?>
              <?php echo $this->getChildHtml("header.links"); ?> 
          </div>
        </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>

<?php 
/* Header12 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_food_3')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-24">
      <div class="top-block">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <?php echo $this->getChildHtml("header.links"); ?>
              <div class="quick-access">
                <div class="language-currency-wrapper">
                  <div class="language-currency-block">
                    <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                    <span class="currency"><?php echo $currency; ?></span>
                    <i class="fa fa-caret-down"></i>
                  </div>
                  <div class="language-currency-dropdown">
                    <?php echo $this->getChildHtml("store_language"); ?> 
                    <?php echo $this->getChildHtml("currency"); ?>
                  </div>
                </div>
                <?php echo $this->getChildHtml("topSearch"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <div class="logo-wrapper">
            <div class="panel header">
                <div class="header content">
                  <?php echo $this->getChildHtml("header24.logo"); ?> 
                  <?php echo $this->getChildHtml("under.logo"); ?> 
                </div>
            </div>
            <?php echo $this->getChildHtml("header.welcome"); ?>
          </div>
          <div class="menu-inner clearfix">
            <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
          </div>
        </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>

<?php
/* Header13 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_furniture')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-19">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-4">
              <?php echo $this->getChildHtml("header.welcome"); ?> 
          </div>
          <div class="panel header col-lg-4 col-md-3">
            <div class="header content">
              <?php echo $this->getChildHtml("header19.logo"); ?> 
              <?php echo $this->getChildHtml("under.logo"); ?> 
            </div>
          </div>
          <div class="col-md-5 col-lg-4 right-block clearfix">
              <div class="language-currency-wrapper">
                <div class="language-currency-block">
                  <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                  <span class="currency"><?php echo $currency; ?></span>
                  <i class="fa fa-caret-down"></i>
                </div>
                <div class="language-currency-dropdown">
                  <?php echo $this->getChildHtml("store_language"); ?> 
                  <?php echo $this->getChildHtml("currency"); ?>
                </div>
              </div>
              <?php echo $this->getChildHtml("topSearch"); ?> 
              <?php echo $this->getChildHtml("header.links"); ?> 
          </div>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <div class="menu-inner clearfix">
            <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
            <?php echo $this->getChildHtml("minicart"); ?>
          </div>
        </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>

<?php
/* Header14 */
if($meigee_helper->getCustomThemeOptionCnf('universal_skins', 'skinheader_perfume')){ ?>
  <div class="header-wrapper">
    <header class="page-header header-19">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-4">
              <?php echo $this->getChildHtml("header.welcome"); ?> 
          </div>
          <div class="panel header col-lg-4 col-md-3">
            <div class="header content">
              <?php echo $this->getChildHtml("header19.2.logo"); ?> 
              <?php echo $this->getChildHtml("under.logo"); ?> 
            </div>
          </div>
          <div class="col-lg-4 col-md-5 right-block clearfix">
              <div class="language-currency-wrapper">
                <div class="language-currency-block">
                  <span class="language-flag"><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($storeManager->getStore()->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($storeManager->getStore()->getName()) ?>"></span>
                  <span class="currency"><?php echo $currency; ?></span>
                  <i class="fa fa-caret-down"></i>
                </div>
                <div class="language-currency-dropdown">
                  <?php echo $this->getChildHtml("store_language"); ?> 
                  <?php echo $this->getChildHtml("currency"); ?>
                </div>
              </div>
              <?php echo $this->getChildHtml("topSearch"); ?> 
              <?php echo $this->getChildHtml("header.links"); ?> 
          </div>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <div class="menu-inner clearfix">
            <?php echo $this->getChildHtml("meigee_mobile_menu"); ?>
            <div class="toggle-nav clearfix"><?php echo $this->getChildHtml("catalog.topnav"); ?> </div>
            <?php echo $this->getChildHtml("minicart"); ?>
          </div>
        </div>
      </div>
      <?php echo $this->getChildHtml("bgslider"); ?>
    </header>
    <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
  </div>
<?php } ?>